--  Todd_Coxeter — Ada 2023 educational package for the Todd–Coxeter
--  coset enumeration algorithm (Todd & Coxeter, 1936).
--  Given a finitely presented group G = <X | R> and a finitely generated
--  subgroup H ≤ G, enumerate the (right) cosets of H in G and build the
--  permutation representation of G acting on those cosets by right
--  multiplication, provided [G : H] is finite and within Max_Cosets.
--  Primary source:
--  https://en.wikipedia.org/wiki/Todd–Coxeter_algorithm
--  Siblings (README only; do not `with`): Coxeter groups, Schreier–Sims
--  (when published).

pragma Ada_2022;

package Todd_Coxeter
  with SPARK_Mode => Off
is

   ------------------------------------------------------------------
   --  Educational capacity bounds
   ------------------------------------------------------------------

   Max_Generators : constant := 8;
   --  Declared generators only (inverses occupy extra table columns).

   Max_Columns : constant := 2 * Max_Generators;
   --  One column per generator and one per formal inverse.

   Max_Relators       : constant := 16;
   Max_Subgroup_Gens  : constant := 8;
   Max_Word_Length    : constant := 48;
   Default_Max_Cosets : constant := 256;
   --  Soft classroom bound; Enumerate refuses to grow past Limit.

   ------------------------------------------------------------------
   --  Words and presentations
   ------------------------------------------------------------------

   --  A word is a finite string over the generator alphabet. Lowercase
   --  letters 'a'..'z' are generators; the matching uppercase letter is
   --  the formal inverse ('A' = a^{-1}). Empty word = identity.
   type Word is record
      Length : Natural := 0;
      Letters : String (1 .. Max_Word_Length) := [others => ' '];
   end record;

   type Word_List is array (Positive range <>) of Word;

   --  Generators is a string of distinct lowercase letters, e.g. "ab".
   --  Relators are words set equal to the identity in G.
   type Presentation is record
      Generators : String (1 .. Max_Generators) := [others => ' '];
      Gen_Count  : Natural := 0;
      Relators   : Word_List (1 .. Max_Relators) := [others => <>];
      Rel_Count  : Natural := 0;
   end record;

   ------------------------------------------------------------------
   --  Coset table / result
   ------------------------------------------------------------------

   subtype Coset_Id is Natural range 0 .. Default_Max_Cosets;
   --  0 = undefined / dead; live cosets are 1 .. Index after success.

   type Coset_Table is
     array (1 .. Default_Max_Cosets, 1 .. Max_Columns) of Coset_Id;

   --  Index = number of live cosets (= [G:H]) when Success.
   --  Table (c, j) = c * g_j for live coset c and column j (gens then
   --  inverses). Success is False when Limit is exceeded before the
   --  table closes (index may be infinite or merely larger than Limit).
   type Result is record
      Index   : Natural := 0;
      Table   : Coset_Table := [others => [others => 0]];
      Columns : Natural := 0;
      Success : Boolean := False;
   end record;

   Invalid_Argument : exception;

   ------------------------------------------------------------------
   --  Constructors / validation helpers
   ------------------------------------------------------------------

   --  Pack a string into a Word. Raises Invalid_Argument if longer than
   --  Max_Word_Length or if any character is not in 'A'..'Z'/'a'..'z'.
   function Make_Word (S : String) return Word
     with Global => null;

   --  Build a presentation from generator letters and relator strings.
   --  Relators is a comma-free list encoded as a Word_List; use
   --  Make_Word on each entry. Raises Invalid_Argument on duplicate /
   --  non-lowercase generators or ill-formed relator letters.
   function Make_Presentation
     (Gens     : String;
      Relators : Word_List) return Presentation
     with Global => null;

   --  True iff every letter of W is a declared generator or its inverse.
   function Word_Is_Valid (Pres : Presentation; W : Word) return Boolean
     with Global => null;

   ------------------------------------------------------------------
   --  Coset enumeration (Todd–Coxeter)
   ------------------------------------------------------------------

   --  Enumerate cosets of the subgroup generated by Subgroup inside the
   --  group given by Pres. Limit caps the number of defined cosets
   --  (educational; typically 128..256).
   --
   --  On success: Result.Success = True, Result.Index = [G : H], and
   --  Result.Table is a complete action table on the live cosets
   --  1 .. Index (coset 1 = H itself).
   --
   --  On failure to close within Limit: Success = False, Index = 0.
   --
   --  Raises Invalid_Argument when Generators are ill-formed, a word
   --  uses an undeclared letter, Rel_Count / subgroup length exceed
   --  capacity, or Limit not in 1 .. Default_Max_Cosets.
   function Enumerate
     (Pres     : Presentation;
      Subgroup : Word_List;
      Limit    : Positive := Default_Max_Cosets) return Result
     with Global => null;

   ------------------------------------------------------------------
   --  Table observers (educational / tests)
   ------------------------------------------------------------------

   --  Column index (1 .. Columns) for generator character Gen, or 0 if
   --  Gen is not among the presentation's generators / inverses.
   function Column_Of
     (Pres : Presentation;
      Gen  : Character) return Natural
     with Global => null;

   --  Right action of Gen on Coset in a successful result, or 0 if the
   --  entry is undefined / arguments are out of range.
   function Action
     (R     : Result;
      Coset : Positive;
      Col   : Positive) return Coset_Id
     with Global => null;

   --  Trace Word from Start through R.Table; return the final coset, or
   --  0 if any step is undefined.
   function Trace
     (R     : Result;
      Pres  : Presentation;
      Start : Positive;
      W     : Word) return Coset_Id
     with Global => null;

end Todd_Coxeter;
